name: Deploy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup KUBECONFIG
        uses: vbem/kubeconfig4sa@v1
        with:
          server:     ${{ secrets.DEV_K8S_ADDRESS }}
          ca-base64:  ${{ secrets.DEV_K8S_CA_BASE64 }}
          token:      ${{ secrets.DEV_K8S_SA_TOKEN }}
          namespace:  default

      - name: Deploy Helm Chart
        run: helm upgrade --install myapp -f customvalues.yaml .
